language: ruby
services:
- postgresql
addons:
  postgresql: '9.6'
cache:
- bundler
before_script:
- bundle exec rails db:reset db:setup db:migrate RAILS_ENV=test
- bundle exec rails assets:precompile
- bundle exec rails db:test:prepare
script:
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: RT87+3lZ+QYLjpfasoFVPVKG82/a1YqshjB1Pb11N3LEHHsbwh7WKj66BlT3qbRNdnjK84FRPqkAyI9Z7SR82ps4q0Ktvh0/bB2X6fbg7YpRQOLyTdtq/x3kHJ6xqf0dgzGqlFzzYRg5lu4JRHOpc2tew3ozSgTzNGLGoqvPmxKZkDOc/2nywVBT3juVmY/tckj8WsGC+4sdl+4/pv86MT4lwvwRFbRNe7JAVh6zQqCxp7Jrd4iBbjZcyczEyPCBzhKyOSZSdALdWxX1XKqXMXzZ/Q+za2z0eW43H12ESi0KIfuZ3nv2Aw5ApbkhiANCVRlje/Lt3YINbLYpDm35m9frtigVDyEVYKetZI8SxwRk+aGlJEuAzHhxcrHyc8zIOoNNxEoK2UgFfHrJViuojy9idu0ZlX4O7Qzg5f4L67Xk1kWrWB6BeUIj/8kkYgUnxnpxjSgG4kFHmSKHoHski9y25H7Egggiy5y/Pur4YSMR8zP8wR1gvneZpYt/hsYTTl4IOIQH9Hm/mkBssFibrmtfYxzGOLO1eNfeF92bTCHJ+P902LXdT8wOK/1Xae7Evq3QUIoJY8Y9xKCP5+3HOZf7lNuc/9u8p8xdd/FZO8XS9fODYXwD/wjJ5gmXObdy30dILa5WEXcYw8+HJu0coDxqSO1wUeuv3/81w75ew7s=
  app: prototype-1440
