language: ruby
services:
  - postgresql
addons:
  postgresql: '9.6'
cache:
  - bundler
before_script:
  - bundle exec rails db:reset db:setup db:migrate RAILS_ENV=test
  - bundle exec rails assets:precompile
  - bundle exec rails db:test:prepare
script:
  - bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: qHlEE4kolYk1R/d23Qur0MkaNR5J6cg6Stg0gLAnjQGIcXrPm5O9Mv27VwmwxFRgRY866jNheCancEPIj+cSxsXgYO9GLvL2o8Ew7EJ+oCz9pAfhRbvI3C7WcY308LPXhHZPk8g1NEsF4QSIBAjojFsoz9WDyIM6e5FGBbdIjqvBOGeH9aQ1hn1FQveQfvOj31CkdSnM1wz1XDHLzW/Bc965svGW/hqbyq/ugY+vfNxSt/rygo3Un+Uuet7lln5dTTXX3LJ9TwYYp2NsqiKtdwdbdQwDBRHKf0ikQ0yla/FGXF+2LBdCjdulhaBp+Ntjg5kJu7xavI14jWa7cX+KYL2SnJZEv6zkq+LfUg+bmBUi1GGqf/Km+efKvg+jE6lBy2leaDllR99siH+U3q6QTlaW7WKZ/ZlBzPSqH3O5nghbzy2E8qBevP2UHCt4N9ZBJoHRqX/gzedqQrAJ5gTMUWDld1U6GCaNgOY4FCiJpkyrzU0envkyeQ296Bfw3KScnkMTcqp4C4smEkLEXab5n+9NRLdQ6RC5G2JPhjFyhhneO6iocpyzIEKjJcdZ/TKh6AMIMjNuItmX788P94jpGX57ozqRcK2qyNA+FYI5kngLTzsZIQxqeqe+uBBcXXdvv7PM2Q0KqMoJoOvEp9DrJ8dZQS+32CGlryvf8nE2LCo=
  app: prototype-1440
